from flask import Flask, request, jsonify, send_file
from reportlab.pdfgen import canvas
import io
import requests

app = Flask(__name__)

def generate_pdf():
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer)
    c.drawString(100, 750, "This is a PDF file generated by the server.")
    c.save()
    buffer.seek(0)
    return buffer

@app.route("/", methods=["POST"])
def handle_request():
    data = request.get_json()
    if not data or "type" not in data:
        return jsonify({"error": "Missing 'type' in request"}), 400

    if data["type"] == 1:
        pdf_buffer = generate_pdf()
        return send_file(
            pdf_buffer,
            as_attachment=True,
            download_name="file.pdf",
            mimetype="application/pdf"
        )

    elif data["type"] == 2:
        return jsonify({"type": 2, "message": "JSON response for type 2"})

    elif data["type"] == 3:
        pdf_buffer = generate_pdf()
        pdf_bytes = pdf_buffer.read()
 
        put_url = "https://frianna-foods.creatio.com/0/OData/DocumentFile(d4f01271-c7d1-4423-9c69-119adf0dc5fe)/Data"

        access_token = ""

        headers = {
            "Content-Type": "application/pdf",
            "Authorization": f"Bearer {access_token}"
        }

        response = requests.put(put_url, headers=headers, data=pdf_bytes)

        if response.status_code in [200, 204]:
            return jsonify({"status": "success", "message": "PDF uploaded to Creatio"})
        else:
            return jsonify({
                "status": "error",
                "message": f"Failed to upload to Creatio. Status code: {response.status_code}",
                "response": response.text
            }), 500

    else:
        return jsonify({"error": "Invalid 'type' value"}), 400

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
