from flask import Flask, request, jsonify, send_file
from reportlab.pdfgen import canvas
import io
import requests

app = Flask(__name__)

def generate_pdf():
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer)
    c.drawString(100, 750, "This is a PDF file generated by the server.")
    c.save()
    buffer.seek(0)
    return buffer

@app.route("/", methods=["POST"])
def handle_request():
    data = request.get_json()
    if not data or "type" not in data:
        return jsonify({"error": "Missing 'type' in request"}), 400

    if data["type"] == 1:
        pdf_buffer = generate_pdf()
        return send_file(
            pdf_buffer,
            as_attachment=True,
            download_name="file.pdf",
            mimetype="application/pdf"
        )

    elif data["type"] == 2:
        return jsonify({"type": 2, "message": "JSON response for type 2"})

    elif data["type"] == 3:
        pdf_buffer = generate_pdf()
        pdf_bytes = pdf_buffer.read()
 
        put_url = "https://frianna-foods.creatio.com/0/OData/DocumentFile(d4f01271-c7d1-4423-9c69-119adf0dc5fe)/Data"

        access_token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IkI1MjZCMzdBRkU2M0NBQjJBOEMwQUQyQUE5OTk5RTQwMUEyQUJBNkRSUzI1NiIsIng1dCI6InRTYXpldjVqeXJLb3dLMHFxWm1lUUJvcXVtMCIsInR5cCI6ImF0K2p3dCJ9.eyJpc3MiOiJjcmVhdGlvLmNvbSIsIm5iZiI6MTc1Mzk4MDgwMSwiaWF0IjoxNzUzOTgwODAxLCJleHAiOjE3NTQwNjcyMDEsImF1ZCI6IkFwcGxpY2F0aW9uQWNjZXNzXzMzODIxNzBmNWI1MDQ2NzA4NjUwZTExZGE2MWJlOThlIiwic2NvcGUiOlsiQXBwbGljYXRpb25BY2Nlc3NfMzM4MjE3MGY1YjUwNDY3MDg2NTBlMTFkYTYxYmU5OGUiXSwiY2xpZW50X2lkIjoiMThBQzI4MzA3RDNDRTlCMjMyNjZBMUM2QTI2M0JCODAiLCJqdGkiOiIyOUZFMTVERkMwMURCQzE4Mjc0N0YxMUFEMUFGNjIwMyIsInByb3A6U3lzQWRtaW5Vbml0SWQiOiI3ZjNiODY5Zi0zNGYzLTRmMjAtYWI0ZC03NDgwYTVmZGY2NDciLCJwcm9wOlJlc291cmNlSWQiOiJBcHBsaWNhdGlvbkFjY2Vzc18zMzgyMTcwZjViNTA0NjcwODY1MGUxMWRhNjFiZTk4ZSIsInByb3A6T3duZXJDbGllbnRJZCI6ImZyaWFubmEtZm9vZHMtaXMiLCJwcm9wOlR5cGUiOiJBcHBsaWNhdGlvbkFjY2VzcyJ9.a0P5UmrYLwxdViwYsE7tqk-Nd3kmcq5uEljDlWw2i8HyNf6IqJuIRW-LDtxe_8gtzPNZzLqeynJPzCtKpMGobTZ8rXByoluPmKbswln8rKJPN4LQbpVeYdJ06tiVarPjyrCqS_N0AmQDENOQ8bro9wNgjmIJoBwmKOTR5TJ_yeaz1RNSdQdKthE-t5DGZdc2EDnCZyL77WMKhafPTjYKGdoP_phMQMDgZyb3J31QH2kzx5QJh0qVGjBK57WP-LghKCxAW2yDAnogglNBnR46Pq5n2hu2g2ejHLQc5DYjk6pY-uruQ_u4I_Wrsv5aI2SbnMNSlXK9cKgpE007yR8nAA"

        headers = {
            "Content-Type": "application/pdf",
            "Authorization": f"Bearer {access_token}"
        }

        response = requests.put(put_url, headers=headers, data=pdf_bytes)

        if response.status_code in [200, 204]:
            return jsonify({"status": "success", "message": "PDF uploaded to Creatio"})
        else:
            return jsonify({
                "status": "error",
                "message": f"Failed to upload to Creatio. Status code: {response.status_code}",
                "response": response.text
            }), 500

    else:
        return jsonify({"error": "Invalid 'type' value"}), 400

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
